# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jetson.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1104, 823)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(700, 0, 401, 221))
        self.groupBox.setObjectName("groupBox")
        self.Camaras = QtWidgets.QGroupBox(self.centralwidget)
        self.Camaras.setGeometry(QtCore.QRect(10, 0, 691, 791))
        self.Camaras.setObjectName("Camaras")
        self.CamaraLat1 = QtWidgets.QLabel(self.Camaras)
        self.CamaraLat1.setGeometry(QtCore.QRect(20, 530, 320, 240))
        self.CamaraLat1.setFrameShape(QtWidgets.QFrame.Box)
        self.CamaraLat1.setObjectName("CamaraLat1")
        self.CamaraCentral = QtWidgets.QLabel(self.Camaras)
        self.CamaraCentral.setGeometry(QtCore.QRect(30, 40, 640, 480))
        self.CamaraCentral.setFrameShape(QtWidgets.QFrame.Box)
        self.CamaraCentral.setObjectName("CamaraCentral")
        self.CamaraLat2 = QtWidgets.QLabel(self.Camaras)
        self.CamaraLat2.setGeometry(QtCore.QRect(350, 530, 320, 240))
        self.CamaraLat2.setFrameShape(QtWidgets.QFrame.Box)
        self.CamaraLat2.setObjectName("CamaraLat2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(700, 220, 401, 571))
        self.groupBox_3.setObjectName("groupBox_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1104, 30))
        self.menubar.setObjectName("menubar")
        self.menuSistema = QtWidgets.QMenu(self.menubar)
        self.menuSistema.setObjectName("menuSistema")
        MainWindow.setMenuBar(self.menubar)
        self.actionCerrar_GUI = QtWidgets.QAction(MainWindow)
        self.actionCerrar_GUI.setObjectName("actionCerrar_GUI")
        self.actionCerrar_Aplicacion = QtWidgets.QAction(MainWindow)
        self.actionCerrar_Aplicacion.setObjectName("actionCerrar_Aplicacion")
        self.actionTest = QtWidgets.QAction(MainWindow)
        self.actionTest.setObjectName("actionTest")
        self.actionTest_Action = QtWidgets.QAction(MainWindow)
        self.actionTest_Action.setObjectName("actionTest_Action")
        self.actionCerrar_GUI_2 = QtWidgets.QAction(MainWindow)
        self.actionCerrar_GUI_2.setObjectName("actionCerrar_GUI_2")
        self.actionCerrar_Aplicacion_2 = QtWidgets.QAction(MainWindow)
        self.actionCerrar_Aplicacion_2.setObjectName("actionCerrar_Aplicacion_2")
        self.menuSistema.addAction(self.actionTest_Action)
        self.menuSistema.addSeparator()
        self.menuSistema.addAction(self.actionCerrar_GUI_2)
        self.menuSistema.addAction(self.actionCerrar_Aplicacion_2)
        self.menubar.addAction(self.menuSistema.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistema Integral de Ayuda a la conduccion - GUI"))
        self.groupBox.setTitle(_translate("MainWindow", "Otros datos"))
        self.Camaras.setTitle(_translate("MainWindow", "Cámaras + Object detection"))
        self.CamaraLat1.setText(_translate("MainWindow", "Camara Lateral 1"))
        self.CamaraCentral.setText(_translate("MainWindow", "Camara central"))
        self.CamaraLat2.setText(_translate("MainWindow", "Camara Lateral 2"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Procesamiento de datos"))
        self.menuSistema.setTitle(_translate("MainWindow", "Sistema"))
        self.actionCerrar_GUI.setText(_translate("MainWindow", "Cerrar GUI"))
        self.actionCerrar_Aplicacion.setText(_translate("MainWindow", "Cerrar Aplicacion"))
        self.actionTest.setText(_translate("MainWindow", "Test"))
        self.actionTest_Action.setText(_translate("MainWindow", "Test Action"))
        self.actionCerrar_GUI_2.setText(_translate("MainWindow", "Cerrar GUI"))
        self.actionCerrar_Aplicacion_2.setText(_translate("MainWindow", "Cerrar Aplicacion"))





def iniciaAplicacion():
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
